package com.prafullkumar.orbit.ui.theme

import androidx.compose.ui.graphics.Color

// ═══════════════════════════════════════════════════════════════════════════
// Orbit Launcher — Minimalist Dark Palette
// Background: near-black, Text: off-white, Accent: muted violet
// ═══════════════════════════════════════════════════════════════════════════

// ── Light scheme ─────────────────────────────────────────────────────────────
val primaryLight = Color(0xFF4E43A3)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE8E4FF)
val onPrimaryContainerLight = Color(0xFF1A0070)
val secondaryLight = Color(0xFF5C5C72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE2E0F5)
val onSecondaryContainerLight = Color(0xFF18182B)
val tertiaryLight = Color(0xFF006B88)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBFE9FF)
val onTertiaryContainerLight = Color(0xFF00202C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8F5FF)
val onBackgroundLight = Color(0xFF1B1A22)
val surfaceLight = Color(0xFFF8F5FF)
val onSurfaceLight = Color(0xFF1B1A22)
val surfaceVariantLight = Color(0xFFE5E1F5)
val onSurfaceVariantLight = Color(0xFF47464F)
val outlineLight = Color(0xFF787880)
val outlineVariantLight = Color(0xFFC8C6D4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF302F38)
val inverseOnSurfaceLight = Color(0xFFF2EFF9)
val inversePrimaryLight = Color(0xFF7C6FE0)
val surfaceDimLight = Color(0xFFD8D6E4)
val surfaceBrightLight = Color(0xFFF8F5FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F0FE)
val surfaceContainerLight = Color(0xFFECEAF8)
val surfaceContainerHighLight = Color(0xFFE6E4F3)
val surfaceContainerHighestLight = Color(0xFFE1DEEE)

// ── Medium-contrast light (same as light for simplicity) ─────────────────────
val primaryLightMediumContrast = primaryLight
val onPrimaryLightMediumContrast = onPrimaryLight
val primaryContainerLightMediumContrast = primaryContainerLight
val onPrimaryContainerLightMediumContrast = onPrimaryContainerLight
val secondaryLightMediumContrast = secondaryLight
val onSecondaryLightMediumContrast = onSecondaryLight
val secondaryContainerLightMediumContrast = secondaryContainerLight
val onSecondaryContainerLightMediumContrast = onSecondaryContainerLight
val tertiaryLightMediumContrast = tertiaryLight
val onTertiaryLightMediumContrast = onTertiaryLight
val tertiaryContainerLightMediumContrast = tertiaryContainerLight
val onTertiaryContainerLightMediumContrast = onTertiaryContainerLight
val errorLightMediumContrast = errorLight
val onErrorLightMediumContrast = onErrorLight
val errorContainerLightMediumContrast = errorContainerLight
val onErrorContainerLightMediumContrast = onErrorContainerLight
val backgroundLightMediumContrast = backgroundLight
val onBackgroundLightMediumContrast = onBackgroundLight
val surfaceLightMediumContrast = surfaceLight
val onSurfaceLightMediumContrast = onSurfaceLight
val surfaceVariantLightMediumContrast = surfaceVariantLight
val onSurfaceVariantLightMediumContrast = onSurfaceVariantLight
val outlineLightMediumContrast = outlineLight
val outlineVariantLightMediumContrast = outlineVariantLight
val scrimLightMediumContrast = scrimLight
val inverseSurfaceLightMediumContrast = inverseSurfaceLight
val inverseOnSurfaceLightMediumContrast = inverseOnSurfaceLight
val inversePrimaryLightMediumContrast = inversePrimaryLight
val surfaceDimLightMediumContrast = surfaceDimLight
val surfaceBrightLightMediumContrast = surfaceBrightLight
val surfaceContainerLowestLightMediumContrast = surfaceContainerLowestLight
val surfaceContainerLowLightMediumContrast = surfaceContainerLowLight
val surfaceContainerLightMediumContrast = surfaceContainerLight
val surfaceContainerHighLightMediumContrast = surfaceContainerHighLight
val surfaceContainerHighestLightMediumContrast = surfaceContainerHighestLight

// ── High-contrast light ───────────────────────────────────────────────────────
val primaryLightHighContrast = Color(0xFF0D004E)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF4E43A3)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF111125)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF383654)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF00253A)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF00516F)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = backgroundLight
val onBackgroundLightHighContrast = onBackgroundLight
val surfaceLightHighContrast = surfaceLight
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = surfaceVariantLight
val onSurfaceVariantLightHighContrast = Color(0xFF232231)
val outlineLightHighContrast = Color(0xFF3F3E47)
val outlineVariantLightHighContrast = Color(0xFF3F3E47)
val scrimLightHighContrast = scrimLight
val inverseSurfaceLightHighContrast = inverseSurfaceLight
val inverseOnSurfaceLightHighContrast = inverseOnSurfaceLight
val inversePrimaryLightHighContrast = inversePrimaryLight
val surfaceDimLightHighContrast = surfaceDimLight
val surfaceBrightLightHighContrast = surfaceBrightLight
val surfaceContainerLowestLightHighContrast = surfaceContainerLowestLight
val surfaceContainerLowLightHighContrast = surfaceContainerLowLight
val surfaceContainerLightHighContrast = surfaceContainerLight
val surfaceContainerHighLightHighContrast = surfaceContainerHighLight
val surfaceContainerHighestLightHighContrast = surfaceContainerHighestLight

// ── Dark scheme — Minimalist launcher palette ─────────────────────────────────
val primaryDark = Color(0xFF7C6FE0) // muted violet accent
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF1A1730) // deep violet surface
val onPrimaryContainerDark = Color(0xFFCEC8FF)
val secondaryDark = Color(0xFF888888) // mid-grey
val onSecondaryDark = Color(0xFF090909)
val secondaryContainerDark = Color(0xFF1A1A1A)
val onSecondaryContainerDark = Color(0xFFE8E8E8)
val tertiaryDark = Color(0xFF5CC8FF)
val onTertiaryDark = Color(0xFF00344A)
val tertiaryContainerDark = Color(0xFF004D6A)
val onTertiaryContainerDark = Color(0xFFBBE9FF)
val errorDark = Color(0xFFFF6B6B)
val onErrorDark = Color(0xFF1F0000)
val errorContainerDark = Color(0xFF5C0000)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF090909) // near-black
val onBackgroundDark = Color(0xFFE8E8E8) // off-white
val surfaceDark = Color(0xFF111111)
val onSurfaceDark = Color(0xFFE8E8E8)
val surfaceVariantDark = Color(0xFF1A1A1A)
val onSurfaceVariantDark = Color(0xFF888888)
val outlineDark = Color(0xFF2A2A2A)
val outlineVariantDark = Color(0xFF333333)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE8E8E8)
val inverseOnSurfaceDark = Color(0xFF090909)
val inversePrimaryDark = Color(0xFF4E43A3)
val surfaceDimDark = Color(0xFF060606)
val surfaceBrightDark = Color(0xFF1A1A1A)
val surfaceContainerLowestDark = Color(0xFF040404)
val surfaceContainerLowDark = Color(0xFF090909)
val surfaceContainerDark = Color(0xFF111111)
val surfaceContainerHighDark = Color(0xFF1A1A1A)
val surfaceContainerHighestDark = Color(0xFF222222)

// ── Medium-contrast dark (same as dark for simplicity) ───────────────────────
val primaryDarkMediumContrast = primaryDark
val onPrimaryDarkMediumContrast = onPrimaryDark
val primaryContainerDarkMediumContrast = primaryContainerDark
val onPrimaryContainerDarkMediumContrast = onPrimaryContainerDark
val secondaryDarkMediumContrast = secondaryDark
val onSecondaryDarkMediumContrast = onSecondaryDark
val secondaryContainerDarkMediumContrast = secondaryContainerDark
val onSecondaryContainerDarkMediumContrast = onSecondaryContainerDark
val tertiaryDarkMediumContrast = tertiaryDark
val onTertiaryDarkMediumContrast = onTertiaryDark
val tertiaryContainerDarkMediumContrast = tertiaryContainerDark
val onTertiaryContainerDarkMediumContrast = onTertiaryContainerDark
val errorDarkMediumContrast = errorDark
val onErrorDarkMediumContrast = onErrorDark
val errorContainerDarkMediumContrast = errorContainerDark
val onErrorContainerDarkMediumContrast = onErrorContainerDark
val backgroundDarkMediumContrast = backgroundDark
val onBackgroundDarkMediumContrast = onBackgroundDark
val surfaceDarkMediumContrast = surfaceDark
val onSurfaceDarkMediumContrast = onSurfaceDark
val surfaceVariantDarkMediumContrast = surfaceVariantDark
val onSurfaceVariantDarkMediumContrast = onSurfaceVariantDark
val outlineDarkMediumContrast = outlineDark
val outlineVariantDarkMediumContrast = outlineVariantDark
val scrimDarkMediumContrast = scrimDark
val inverseSurfaceDarkMediumContrast = inverseSurfaceDark
val inverseOnSurfaceDarkMediumContrast = inverseOnSurfaceDark
val inversePrimaryDarkMediumContrast = inversePrimaryDark
val surfaceDimDarkMediumContrast = surfaceDimDark
val surfaceBrightDarkMediumContrast = surfaceBrightDark
val surfaceContainerLowestDarkMediumContrast = surfaceContainerLowestDark
val surfaceContainerLowDarkMediumContrast = surfaceContainerLowDark
val surfaceContainerDarkMediumContrast = surfaceContainerDark
val surfaceContainerHighDarkMediumContrast = surfaceContainerHighDark
val surfaceContainerHighestDarkMediumContrast = surfaceContainerHighestDark

// ── High-contrast dark ────────────────────────────────────────────────────────
val primaryDarkHighContrast = Color(0xFFEFEBFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF7C6FE0)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFF5F3FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF888888)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFECF5FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF59C9FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFF6B6B)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = backgroundDark
val onBackgroundDarkHighContrast = onBackgroundDark
val surfaceDarkHighContrast = surfaceDark
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = surfaceVariantDark
val onSurfaceVariantDarkHighContrast = Color(0xFFF7F5FF)
val outlineDarkHighContrast = Color(0xFFC9C6D7)
val outlineVariantDarkHighContrast = Color(0xFFC9C6D7)
val scrimDarkHighContrast = scrimDark
val inverseSurfaceDarkHighContrast = inverseSurfaceDark
val inverseOnSurfaceDarkHighContrast = inverseOnSurfaceDark
val inversePrimaryDarkHighContrast = inversePrimaryDark
val surfaceDimDarkHighContrast = surfaceDimDark
val surfaceBrightDarkHighContrast = surfaceBrightDark
val surfaceContainerLowestDarkHighContrast = surfaceContainerLowestDark
val surfaceContainerLowDarkHighContrast = surfaceContainerLowDark
val surfaceContainerDarkHighContrast = surfaceContainerDark
val surfaceContainerHighDarkHighContrast = surfaceContainerHighDark
val surfaceContainerHighestDarkHighContrast = surfaceContainerHighestDark
